### ISSUE TITLE
Upgraded from  a2 annotations and get errors

### ISSUE THREAD

**Issue by amcdnl** [shuhei/babel-preset-angular2#1]
I was using your previous projects:

```
"babel-core": "^6.8.0",
"babel-plugin-angular2-annotations": "^5.1.0",
"babel-plugin-transform-decorators-legacy": "^1.3.4",
"babel-plugin-transform-flow-strip-types": "^6.8.0",
```

and upgraded to this project and get the following error now:

```
TypeError: Cannot read property 'query' of null(…) "TypeError: Cannot read property 'query' of null
    at eval (http://localhost:8080/jspm_packages/npm/@angular/compiler@2.0.0-rc.1/src/provider_parser.js:360:37)
    at Array.forEach (native)
    at eval (http://localhost:8080/jspm_packages/npm/@angular/compiler@2.0.0-rc.1/src/provider_parser.js:359:31)
    at Array.forEach (native)
    at _getContentQueries (http://localhost:8080/jspm_packages/npm/@angular/compiler@2.0.0-rc.1/src/provider_parser.js:355:16)
    at new ProviderElementContext (http://localhost:8080/jspm_packages/npm/@angular/compiler@2.0.0-rc.1/src/provider_parser.js:55:32)
    at TemplateParseVisitor.visitElement (http://localhost:8080/jspm_packages/npm/@angular/compiler@2.0.0-rc.1/src/template_parser.js:282:31)
    at HtmlElementAst.visit (http://localhost:8080/jspm_packages/npm/@angular/compiler@2.0.0-rc.1/src/html_ast.js:59:83)
    at eval (http://localhost:8080/jspm_packages/npm/@angular/compiler@2.0.0-rc.1/src/html_ast.js:76:29)
    at Array.forEach (native)"
```

Is this supposed to be compatible with the above?

**Comment by shuhei** [comment]
Hmm, I have no idea with only the stack trace. How did you upgrade your project exactly? Would you mind posting the diff?

**Comment by amcdnl** [comment]
Sorry for lack of details, not sure where to start given the vague-ness of the error.

**Comment by shuhei** [comment]
1. Please make sure that it works if you use the plugins directly instead of this preset.
2. If 1. works, plugin/preset ordering is the cause. Please post your `.babelrc`.

**Comment by amcdnl** [comment]
Yes, works with the setup of:
- babel-plugin-transform-decorators-legacy
- babel-plugin-angular2-annotations
- babel-plugin-transform-decorators-legacy
- babel-plugin-transform-flow-strip-types

switched to `babel-preset-angular2` with the following babel config:

```
"babel": {
    "sourceMaps": false,
    "presets": [
      "es2015",
      "stage-0",
     "angular2"
    ],
    "plugins": [
      "external-helpers",
      "babel-plugin-transform-decorators-legacy"
    ],
    "moduleIds": false,
    "comments": true,
    "compact": false
  }
```

and got the errors above.

**Comment by shuhei** [comment]
Thanks!

`babel-plugin-transform-decorators-legacy` is already included in the `angular2` preset. What if you remove it from `plugins`?

**Comment by amcdnl** [comment]
Really odd, removing that fixed it. I left it there thinking it would de-dupe and wanted to keep that explicit. Sorry to bother you!

**Comment by shuhei** [comment]
No problem!

`plugins` are applied first and then plugins in `presets` are applied. That's why `decorators-legacy` messed up your JS before `angular2-annotations` was applied. The ordering is hard to configure. So I made this preset :-)

**Comment by amcdnl** [comment]
got it! didn't know order was actually applied, i must have just magically got mine right haha
